// Generated by CoffeeScript 1.4.0
var $loader, input, online, output, passphrase, send_button;

send_button = $('#send');

input = $('#input');

output = $('#output');

passphrase = $('#pass');

online = $('#online');

$loader = $("<img src=\"loading.gif\" alt=\"Loading...\" title=\"Loading...\" style=\"margin-right:15px;\" />");

$(function() {
  /*
    Creates a random string
    @returns {string} A random string
  */

  var hashObj, password, randomString;
  randomString = function() {
    var chars, i, randomstring, rnum, string_length;
    chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXTZabcdefghiklmnopqrstuvwxyz";
    string_length = 128;
    randomstring = "";
    i = 0;
    while (i < string_length) {
      rnum = Math.floor(Math.random() * chars.length);
      randomstring += chars.substring(rnum, rnum + 1);
      i++;
    }
    return randomstring;
  };
  password = void 0;
  if (!sessionStorage.isConnected) {
    hashObj = new jsSHA(randomString(), "ASCII");
    password = hashObj.getHash("SHA-512", "HEX");
    $.jCryption.authenticate(password, "crypt.php?generateKeypair=true", "crypt.php?handshake=true", (function(AESKey) {
      $("#text, #send,#clearSessionStorage").attr("disabled", false);
      $("#status").html("<span style=\"font-size: 16px;\">Let's Rock!</span>");
      sessionStorage.setItem("isConnected", "1");
      return sessionStorage.setItem("password", password);
    }), function() {
      return alert("Authentication failed");
    });
  } else {
    $("#text, #send,#clearSessionStorage").attr("disabled", false);
    $("#status").html("<span style=\"font-size: 16px;\">Let's Rock!</span>");
    password = sessionStorage.password;
  }
  $("#send").click(function() {
    var encryptedString;
    encryptedString = $.jCryption.encrypt($("#text").val(), password);
    $("#log").prepend("\n").prepend("----------");
    $("#log").prepend("\n").prepend("Plaintext: " + $("#text").val());
    $("#log").prepend("\n").prepend("Encrypted: " + encryptedString);
    return $.ajax({
      url: "crypt.php?",
      dataType: "json",
      type: "POST",
      data: {
        jCryption: encryptedString
      },
      success: function(response) {
        $("#log").prepend("\n").prepend("Served sent: " + response.data);
        return $("#log").prepend("\n").prepend("Decrypted: " + $.jCryption.decrypt(response.data, password));
      }
    });
  });
  return $("#clearSessionStorage").click(function(e) {
    sessionStorage.clear();
    return window.location = window.location;
  });
});
